### ISSUE TITLE
two toggles in the same svelte file: second does not work

### ISSUE THREAD

**Issue by jeromecc** [metonym/svelte-toggle#16]
Hi!
When I use more than one Toggle components in the same```
 svelte file, the second one does not work.

```
<script>                                                                        
  import Toggle from "svelte-toggle";                                           
  let toggled;                                                                  
  let toggled2;                                                                 
</script>                                                                  
<Toggle bind:toggled />                                                                                                                           
Toggled? {toggled}                                                              
<Toggle bind:toggled2 />                                                        
Toggled2? {toggled2}
```
Here toggles2 remains undefined.
If I define both variables to false, toggled 2 remains false even when i toggle the component.

See this repl https://svelte.dev/repl/03dfe3c0bb1b4e818edc50353b6ff24b?version=3.46.4 based on your example.

Thanks.

**Comment by metonym** [comment]
If you're using the short syntax for the `bind:variable` directive, the name of `variable` must be the same as the prop.

```svelte
<Toggle bind:toggled={toggled2} /> 
```

https://svelte.dev/repl/2f709e6b1c0a442e83b183157c4791e5?version=3.46.4

**Comment by jeromecc** [comment]
Thank you so much. I'm still a bit of a rookie about Svelte. Have a great weekend!
