### ISSUE TITLE
Usage with writable store

### ISSUE THREAD

**Issue by vegeta897** [metonym/svelte-toggle#17]
Is there a clean way to bind the toggle to a writable store?

The following does not work:

```svelte
<script>
import { writable } from 'svelte/store'
import Toggle from 'svelte-toggle'

const toggled = writable(false)
</script>

<Toggle bind:toggled />
```

Neither does `bind:$toggled`, `bind:value={$toggled}` or `bind:checked={$toggled}`.

My workaround is to add the `toggled` property and listen to the `toggle` event to update the store:

```svelte
<script>
import { writable } from 'svelte/store'
import Toggle from 'svelte-toggle'

const toggled = writable(false)

function onToggle({ detail }) {
  toggled.set(detail)
}

</script>

<Toggle toggled={$toggled} on:toggle={onToggle} />
```

This isn't terrible, but I wonder why it's not as simple as binding a store to a native checkbox, like so:

```svelte
<script>
import { writable } from 'svelte/store'
import Toggle from 'svelte-toggle'

const toggled = writable(false)
</script>

<input type="checkbox" bind:checked={$toggled} />
```

**Comment by metonym** [comment]
Hi there, I'm not able to repro the issue.

Can you verify if the example below works for you?

```svelte
<script>
  import Toggle from "svelte-toggle";
  import { writable } from "svelte/store";
	
  const toggled = writable(false);
</script>

<Toggle bind:toggled={$toggled} />

{$toggled}
```

See the Svelte REPL: https://svelte.dev/repl/0cb9f13c2a284386b0631968d15b38f3?version=3.46.4

**Comment by vegeta897** [comment]
🤦‍♂️ I need to go back to svelte 101...

I tried everything except `bind:toggled={$toggled}` and I have no idea why.

Thanks for the super fast reply, sorry to bug you!
