### ISSUE TITLE
classic styling?

### ISSUE THREAD

**Issue by quantuminformation** [metonym/svelte-toggle#2]
seen

![image](https://user-images.githubusercontent.com/216566/91256823-9e7f9d80-e768-11ea-8907-09b26bbd5417.png)

might be better for users to see it like
![image](https://user-images.githubusercontent.com/216566/91256866-bce59900-e768-11ea-9291-ab585a4f9dfc.png)

**Comment by metonym** [comment]
Agreed. Open to PRs in this regard.

Also, another idea would be to make the component "styleless" by default, leaving styling up to the consumer.

**Comment by quantuminformation** [comment]
it didnt work for me and its too much bloat from react

**Comment by metonym** [comment]
@quantuminformation in which case I'm open to exploring the classic UI

Thinking aloud here... I see the benefit of having a classic UI look while also giving the freedom to style it however way you want it. Going even further, the Toggle could be "renderless" (i.e. a slot that passes state as props)

- `Toggle` base export (unstyled)
- `ToggleSwitch` (classic UI)

**Comment by quantuminformation** [comment]
nice one thx, I think people like me are just lazy and want it to look good and you to do the thinking

**Comment by metonym** [comment]
@quantuminformation `svelte-toggle` has been redesigned and released in v1.0.0. It incorporates changes that address several issues you've raised. Let me know if you encounter any issues.

The [demo](https://metonym.github.io/svelte-toggle/) contains example use cases.

PR #5

- refactor default toggle styles to conform to the classic "switch" UI for boolean states (#2)
- allow Toggle UI colors to be customized (`switchColor`, `toggledColor`, `untoggledColor`) (#3)
- allow label to be visually hidden (set `hideLabel` to `true`) (#4)
- default `label` text is changed from "Toggle label" to "Label"
- make on/off labels optional (by default they're undefined)
- add small variant for `Toggle` switch size
- extract core component logic into standalone `ToggleCore` which instruments the accessibility aspects (this component is "renderless" in that it does not have any styles or markup)
  refactor default `Toggle` to use `ToggleCore`

**Breaking Changes**

- `on` / `off` props are optional and must be truthy to use named slots

**Comment by quantuminformation** [comment]
Wow you are fast man! great work!
