### ISSUE TITLE
Vite: Conflicting results in svelte module resolution.

### ISSUE THREAD

**Issue by YonicDev** [metonym/svelte-toggle#23]
The current resolution for svelte modules used for the toggle component has some conflicting results. This is not a breaking problem, but it may cause them in the future.

A good alternative would be to use conditional exports [as explained here](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve), since they're supported by Node and bundlers like Vite and simplify the implementation for those resolutions.

**Comment by metonym** [comment]
Thank you for the heads up.

The library has been updated to only ship the source Svelte files, and use `type="module"` in `package.json. Published as v4.0.0.
