### ISSUE TITLE
Can we have a prop to change the background colour?

### ISSUE THREAD

**Issue by quantuminformation** [metonym/svelte-toggle#3]

**Comment by quantuminformation** [comment]
Also if the button loses focus the border is different:

![image](https://user-images.githubusercontent.com/216566/91282032-12ca3900-e789-11ea-86b6-d4486ef0d7d0.png)
![image](https://user-images.githubusercontent.com/216566/91282051-19f14700-e789-11ea-9ff3-e25fe5f69f89.png)

**Comment by metonym** [comment]
Currently, you will need to override the existing styles of the component. This can be done either with a global class or passing a "style" attribute to the component.

```jsx
<Toggle style="background-color: red" />
```

**Comment by metonym** [comment]
Added in 5c49d49
