### ISSUE TITLE
Support `trueValue` and `falseValue`

### ISSUE THREAD

**Issue by dragomano** [metonym/svelte-toggle#39]
Please add the ability to override the values sent by this component within the form.

Example implementation: https://github.com/vueform/toggle

Example code:
```svelte
<Toggle bind:status label="Toggle" trueValue="on" falseValue="off" />
```

**Comment by metonym** [comment]
Hey there, this seems to be supported by switch descriptors: https://github.com/metonym/svelte-toggle?tab=readme-ov-file#switch-descriptors

```svelte
<Toggle on="On" off="Off" />
```

**Comment by dragomano** [comment]
I solved it this way:
```svelte
  <Toggle bind:toggled />
  <input type="hidden" {name} bind:value={toggled} />
```
