### ISSUE TITLE
prop to remove label entirely

### ISSUE THREAD

**Issue by quantuminformation** [metonym/svelte-toggle#4]
No way to remove the label even if empty

![image](https://user-images.githubusercontent.com/216566/91279889-5c655480-e786-11ea-8ecd-8cd370eed815.png)

**Comment by metonym** [comment]
The label is important for accessibility reasons.

However, we could define a `hideLabel` prop that visually hides the element. Would that work for your use case?

**Comment by quantuminformation** [comment]
yeah thx

**Comment by metonym** [comment]
Added in 5c49d4977cddb0e7669bec68a4c664adbbe79324
